language: android
dist: trusty
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=26
    - ANDROID_BUILD_TOOLS=26.0.2
    - OWNER=${TRAVIS_REPO_SLUG%/*}
    - DEV=${OWNER/pymq/dev}
    - BRANCH=${TRAVIS_BRANCH/master/}
    - TAG=${DEV}${BRANCH:+_}${BRANCH}

before_install:
  - chmod +x gradlew

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS

    # The SDK version used to compile your project
    - android-$ANDROID_API

    # Additional components
    #- extra-google-google_play_services
    - tools
    - platform-tools
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-x86-android-26
    #- sys-img-armeabi-v7a-android-17
  licenses:
    - android-sdk-license-.+


branches:
  except:
    - /^travis-.*-build$/

before_script:
  - yes | sdkmanager --licenses

script: ./gradlew assembleDebug

before_deploy:
  - ln -s app/build/outputs/apk/debug/app-debug.apk narsoe-${TAG}-build.apk
  - git tag -f travis-${TAG}-build
  - git remote add gh
    https://${OWNER}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push gh :travis-${TAG}-build || true
  - git push -f gh travis-${TAG}-build
  - git remote remove gh


deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: narsoe-${TAG}-build.apk
  skip_cleanup: true
  name: narsoe development build (${TRAVIS_BRANCH})
  body: Automatic narsoe development build of $TRAVIS_BRANCH branch
    (commit $TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  #draft: true
  overwrite: true #
  target_commitish: $TRAVIS_COMMIT #
  on:
    #tags: true
    tags: false #
    all_branches: true #

