language: android
dist: trusty
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=23
    - ANDROID_BUILD_TOOLS=23.0.3
    - OWNER=${TRAVIS_REPO_SLUG%/*}
    - DEV=${OWNER/pymq/dev}
    - BRANCH=${TRAVIS_BRANCH/master/}
    - TAG=${DEV}${BRANCH:+_}${BRANCH}

before_install:
  - chmod +x gradlew

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra
  licenses:
    - android-sdk-license-.+

branches:
  except:
    - /^travis-.*-build$/

before_script:
  - yes | sdkmanager "tools"
  - yes | sdkmanager "platform-tools"
  - yes | sdkmanager "build-tools;$ANDROID_BUILD_TOOLS"
  - yes | sdkmanager "platforms;android-$ANDROID_API"
#  - yes | sdkmanager --licenses

script: ./gradlew assembleDebug

before_deploy:
  - ln -s app/build/outputs/apk/debug/app-debug.apk narsoe-${TAG}-build.apk
  - git tag -f travis-${TAG}-build
  - git remote add gh_origin https://${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push gh_origin :travis-${TAG}-build || true
  - git push -f gh_origin travis-${TAG}-build
  - git remote remove gh_origin


deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: narsoe-${TAG}-build.apk
  skip_cleanup: true
  name: narsoe development build (${TRAVIS_BRANCH})
  body: Automatic narsoe development build of $TRAVIS_BRANCH branch
    (commit $TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  #draft: true
  overwrite: true #
  target_commitish: $TRAVIS_COMMIT #
  on:
    #tags: true
    tags: false #
    all_branches: true #

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache